services:
  - type: web
    name: asterisk-
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: "gunicorn api_server:app"
